### ISSUE TITLE
once() method not working correctly on IE 11

### ISSUE THREAD

**Issue by dhAlcojor** [ealush/vent#2]
Everything is working, we're using the vent.min.es5.js and polyfills, so it works, there's no error. But the once() method isn't behaving as expected.

In one of our unit tests, we use the once() method to register an event and then trigger it twice. The handler should be running only once, but it's actually running twice. This only happens on IE 11, of course.

Anyone having the same issue?

**Comment by dhAlcojor** [comment]
Solved it. I had to include another polyfill for Array.prototype.includes: https://www.npmjs.com/package/polyfill-array-includes

**Comment by ealush** [comment]
Thank you for this issue, glad to see that you managed to solve it.  LMK if there's anything else I can help with.
